# https://packaging.python.org/en/latest/guides/writing-pyproject-toml/
# https://peps.python.org/pep-0518/

[project]
name = "a-mark"
version = "0.3.0"
authors = [
    {name = "Mateusz A.", email = "Matthew.A@tutanota.com"},
]
maintainers = [
    {name = "Mateusz A.", email = "Matthew.A@tutanota.com"}
]
description = "Adding watermarks to images (batch mode by default)"
readme = "README.md"
dependencies = [
    "pillow~=12.1",
    "numpy~=2.4",
    "black~=26.3",
    "pre-commit~=4.5",
]

[project.urls]
Homepage = "https://github.com/a-matthew/a-mark"
Documentation = "https://github.com/a-matthew/a-mark"
Repository = "https://github.com/a-matthew/a-mark.git"
Issues = "https://github.com/a-matthew/a-mark/issues"
Changelog = "https://github.com/a-matthew/a-mark/releases"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
line_length = 88